echo "Copying NonVolatile Memory"
mkdir ../HeepESP8266Boards/HeepESPPackage/libraries/ESP8266_NonVolatileMemory
cp Firmware/ServerlessFirmware/ESP8266_NonVolatileMemory.cpp ../HeepESP8266Boards/HeepESPPackage/libraries/ESP8266_NonVolatileMemory/ESP8266_NonVolatileMemory.cpp
cp Firmware/ServerlessFirmware/ESP8266_NonVolatileMemory.h ../HeepESP8266Boards/HeepESPPackage/libraries/ESP8266_NonVolatileMemory/ESP8266_NonVolatileMemory.h

echo "Copying Heep Comms"
mkdir ../HeepESP8266Boards/HeepESPPackage/libraries/ESP8266_HeepComms
cp Firmware/ServerlessFirmware/ESP8266_HeepComms.cpp ../HeepESP8266Boards/HeepESPPackage/libraries/ESP8266_HeepComms/ESP8266_HeepComms.cpp
cp Firmware/ServerlessFirmware/ESP8266_HeepComms.h ../HeepESP8266Boards/HeepESPPackage/libraries/ESP8266_HeepComms/ESP8266_HeepComms.h

echo "Copying Timer"
mkdir ../HeepESP8266Boards/HeepESPPackage/libraries/Arduino_Timer
cp Firmware/ServerlessFirmware/Arduino_Timer.cpp ../HeepESP8266Boards/HeepESPPackage/libraries/Arduino_Timer/Arduino_Timer.cpp
cp Firmware/ServerlessFirmware/Arduino_Timer.h ../HeepESP8266Boards/HeepESPPackage/libraries/Arduino_Timer/Arduino_Timer.h

echo "Adding Library Includes"
cp Firmware/ServerlessFirmware/AutoGeneratedInfo.h ../HeepESP8266Boards/HeepESPPackage/tools/sdk/include/AutoGeneratedInfo.h
cp Firmware/ServerlessFirmware/CommonDataTypes.h ../HeepESP8266Boards/HeepESPPackage/tools/sdk/include/CommonDataTypes.h
cp Firmware/ServerlessFirmware/Heep_API.h ../HeepESP8266Boards/HeepESPPackage/tools/sdk/include/Heep_API.h

echo "Building Library"
make clean -C Firmware/ServerlessFirmware/LibraryBuilders/ESP/
make -C Firmware/ServerlessFirmware/LibraryBuilders/ESP/
cp Firmware/ServerlessFirmware/LibraryBuilders/ESP/libHeep.a ../HeepESP8266Boards/HeepESPPackage/tools/sdk/lib/libHeep.a

echo "Compressing Board File"
tar -cvjSf ../HeepESP8266Boards/HeepESPPackage-1.0.0.tar.bz2 ../HeepESP8266Boards/HeepESPPackage

ls -l ../HeepESP8266Boards/HeepESPPackage-1.0.0.tar.bz2
shasum -a 256 ../HeepESP8266Boards/HeepESPPackage-1.0.0.tar.bz2