#define NUMBER_OF_CONTROLS 2
#define ALLOWED_VERTICES 4

#define CLIENT_NAME_MEMORY_SIZE 10
#define CONTROL_NAME_MEMORY_SIZE 10
#define CLIENT_STRING_MEMORY_SIZE 100
#define CLIENT_ICON_NAME_LENGTH 5
#define IP_ADDRESS_LENGTH 16

#define PLC_OUTPUT_BUFFER_SIZE 200
#define PLC_INPUT_BUFFER_SIZE 200