// #define ONPC
#define PC_ARDUINO_TEST

#ifndef ONPC
#ifndef PC_ARDUINO_TEST
#include "Arduino.h"
#endif
#endif

#define CONTROL_VAL_NAME_BUFFER_LEN 14
#define CONTROL_OUT_STRING_BUFFER_LEN 50
#define VERTEX_CONTROL_NAME_LENGTH 14
#define VERTEX_IP_NAME_LENGTH 16
#define OUT_DATA_CONTROL_NAME_LENGTH 14
#define OUT_DATA_IP_NAME_LENGTH 16
#define CLIENT_NAME_BUFFER_LEN 16
#define CLIENT_IP_NAME_LENGTH 16
#define CLIENT_OUT_STRING_BUFFER_LEN 150