#pragma once
#include "AutoGeneratedInfo.h"

// Define the input and output buffers for global accessibility
extern unsigned char outputBuffer [OUTPUT_BUFFER_SIZE];
extern unsigned int outputBufferLastByte;

extern unsigned char inputBuffer [INPUT_BUFFER_SIZE];
extern unsigned int inputBufferLastByte;

struct HeepIPAddress
{
	unsigned char Octet4;
	unsigned char Octet3;
	unsigned char Octet2;
	unsigned char Octet1;
};

struct Vertex
{
	unsigned long rxID;
	unsigned long txID;

	unsigned char rxControlID;
	unsigned char txControlID;

	struct HeepIPAddress rxIPAddress;
};

struct Vertex_Byte
{
	heepByte rxID [STANDARD_ID_SIZE];
	heepByte txID [STANDARD_ID_SIZE];

	unsigned char rxControlID;
	unsigned char txControlID;

	struct HeepIPAddress rxIPAddress;
};

struct Control
{
	unsigned char controlID;
	unsigned char controlDirection;
	unsigned char controlType; // 0 = OnOff, 1 = Range, 2 = Buffer
	unsigned char highValue;   // Maximum value of a range, or the highest index in a buffer
	unsigned char lowValue; 
	unsigned char curValue;
	unsigned char controlFlags;
	char* controlName;

	heepByte* controlBuffer; // The memory must be allocated by the user, and assigned to the buffer
};